# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('uploadByFile', models.BooleanField(verbose_name='\u662f\u5426\u901a\u8fc7\u6587\u4ef6\u4e0a\u4f20')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('money', models.IntegerField(verbose_name='\u6b20\u6b3e')),
                ('deadline', models.DateTimeField(verbose_name='\u622a\u6b62\u65e5\u671f')),
                ('delay', models.IntegerField(verbose_name='\u671f\u9650')),
                ('inFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.File')),
            ],
        ),
        migrations.DeleteModel(
            name='resultInfo',
        ),
        migrations.DeleteModel(
            name='userInfo',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='version',
            name='versions',
            field=models.CharField(max_length=20, verbose_name='\u7248\u672c\u53f7'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
