# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180524_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='versions',
            new_name='version',
        ),
        migrations.AddField(
            model_name='file',
            name='fileName',
            field=models.CharField(default='unknown_file', max_length=100, verbose_name='\u6587\u4ef6\u540d'),
            preserve_default=False,
        ),
    ]
