# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180524_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='money',
            new_name='debt',
        ),
        migrations.AddField(
            model_name='info',
            name='sex',
            field=models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973')], null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='info',
            name='tel',
            field=models.CharField(max_length=20, null=True, verbose_name='\u624b\u673a'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='result',
            field=models.IntegerField(choices=[(1, '\u672a\u5904\u7406'), (2, '\u6b63\u5728\u5904\u7406'), (3, '\u5df2\u5904\u7406')], default=1, verbose_name='\u5904\u7406\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='file',
            name='submit_time',
            field=models.DateTimeField(verbose_name='\u4e0a\u4f20\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploadByFile',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u901a\u8fc7\u6587\u4ef6\u4e0a\u4f20>?'),
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='result',
            field=models.IntegerField(choices=[(1, '\u672a\u5904\u7406'), (2, '\u6b63\u5728\u5904\u7406'), (3, '\u5df2\u5904\u7406')], default=1, verbose_name='\u5904\u7406\u7ed3\u679c'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
