# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180524_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='importdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5bfc\u5165\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
